apiVersion: v1
kind: Service
metadata:
  name: juice-loadbalancer
spec:
  selector:
    app.kubernetes.io/instance: juice-balancer-multi-juicer
    app.kubernetes.io/name: juice-balancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
